### ISSUE TITLE
Reaching Nirvana, one commit at a time

### ISSUE THREAD

**Issue by pierswarmers** [BrisPHP/meetups#10]
I'm plagued with the human condition. I get distracted, I fear the complexities in life and I worry what people think. Not problem, I've found the solution to my woes in… GIT. Come with me on a journey to find out how GIT can be your guide on the path to enlightenment.

This is supposed to be fun talk about coding in a team/community and how git often sits in the middle of that. Sorry, peeps... it's not a specific PHP talk. But I am a PHP coder if that helps ;)

**Comment by ndench** [comment]
Thanks for the offer @pierswarmers! Definitely sounds like an interesting talk. At the moment we're just waiting on a couple others to confirm that they'll be talking at the next meetup. If we don't get confirmation soon though, would be happy to give this talk at the end of the month?

**Comment by pierswarmers** [comment]
Sure. No problem at all.

**Comment by ndench** [comment]
Hey @pierswarmers, the speaker we were waiting on confirmation for will actually be on leave during the meetup. So if you're keen we can lock you in for the final talk of the night on the 31st?

**Comment by pierswarmers** [comment]
Sound great... count me in. I have it ready to go.

**Comment by dkcwd** [comment]
I recommend coming along for this talk, I enjoyed it thoroughly at a meetup in Sydney. 👍

**Comment by ndench** [comment]
Great talk @pierswarmers I really enjoyed it. [Here's a link](https://docs.google.com/presentation/d/1yP4tCLOlGInqsmProuuSZAFvSrGoGhxw5EblOUQRFco) to the presentation so others can find it.
