### ISSUE TITLE
Refactoring high stakes code smoothly

### ISSUE THREAD

**Issue by theHarvester** [BrisPHP/meetups#12]
I can do a talk on our approach to refactoring mission critical code in a production system without breaking anything.

**Comment by dpdme** [comment]
Sounds great @theHarvester

**Comment by ndench** [comment]
This talk has been scheduled for our next meetup: https://www.meetup.com/BrisPHP/events/253361238/

**Comment by ndench** [comment]
Great talk @theHarvester! Here's a link to the presentation on Google Drive: https://docs.google.com/presentation/d/1IB8worymjqL9Xg_wmTAKSg12646Ctra8SyskSwe8bI0/edit?usp=sharing

**Comment by dpdme** [comment]
Awesome. Ill share it with the crew.
