### ISSUE TITLE
Containers - How to use them in development and production

### ISSUE THREAD

**Issue by benfreke** [BrisPHP/meetups#14]
I'm sure most people have played with Docker, but most would not have ended up with a good workflow that uses containers both locally and for production. 

We've recently deployed our first service to production using containers but I'd be very interested to see how other people are doing this to compare methods and hopefully get to something approaching best practice, both for single person teams and larger devops teams.

**Comment by carlo111** [comment]
Hi Ben

Could only do the epub ( file size issue)

if you want some few more PDF let me know.

Carlo

**Comment by benfreke** [comment]
Hi @carlo111 

I don't think you can use github to distribute files :) If you have a link to where they live on the Internet that would be great to see?

**Comment by dpdme** [comment]
Hi @benfreke This is something we may be able to present on.  I'll have a chat to the DevOps crew and see what I can rustle up.

**Comment by ndench** [comment]
This talk has been scheduled for our next meetup on the 30th of August: https://www.meetup.com/BrisPHP/events/253361238/

**Comment by ndench** [comment]
Thanks for the talk @dpdme! Would you be able to share a link to your slides?

**Comment by benfreke** [comment]
Unfortunately I couldn't make it last night, so super keen to see the slides @dpdme please?

**Comment by s3than** [comment]
[Building Containers for development and production.pptx](https://github.com/BrisPHP/meetups/files/2338393/Building.Containers.for.development.and.production.pptx)

Any questions related to the talk give me a yell

**Comment by ndench** [comment]
Oops, got your GitHub confused @s3than. I'll redirect my thanks at you for being the one that gave the talk :joy:

**Comment by benfreke** [comment]
Hi @s3than

Just a little confused about how you would seperate the development and production builds? I'm guessing you would have 2 separate Dockerfiles so you can call the appropriate one via a script? 

The multilayer example was great, really clear on the benefits of that :)

**Comment by s3than** [comment]
Hi @benfreke 

Apologies for the delay

The idea is that you would use a single Dockerfile that builds up and re-uses the previous stages.

So for example, as a very simple workflow

![docker stages simple](https://user-images.githubusercontent.com/6881648/46252501-b54de480-c4ac-11e8-996e-86390a706692.png)

The development image could be called by 

```
docker build -t dev-image .
```
The production image
```
docker build --target production -t prod-image .
```

The idea is to treat each stage in a similar fashion to the layers example.

**Comment by benfreke** [comment]
Got it. For some reason I didn't consider that as an option. Makes complete sense now, thanks!
