### ISSUE TITLE
Using gitlab for PHP developers

### ISSUE THREAD

**Issue by VladimirAus** [BrisPHP/meetups#16]
Gitlab is a great alternative to GitHub and Bitbucket code management services but what exactly does it bring to the table for php developers.

Agenda:
* What is Gitlab?
* Differences to the other services.
* Gitlab for PHP projects
* Gitlab CI
* Contributing to GitLab

**Comment by ndench** [comment]
@VladimirAus this sounds interesting, I would be particularly interested in the differences between Gitlab and GitHub. Just to be clear, are you offering to do this talk or requesting to hear it?

**Comment by VladimirAus** [comment]
That's talk offer

**Comment by benfreke** [comment]
I miss Gitlab. Loved the dismissed comments feature.

**Comment by VladimirAus** [comment]
Sure @ndench . Can do.

**Comment by VladimirAus** [comment]
@ndench yep. See you on 29th

**Comment by ndench** [comment]
Thanks for the talk @VladimirAus! Can you add a link for you slides to this issue?

**Comment by VladimirAus** [comment]
"Gitlab for PHP developers" slides are available here: https://www.slideshare.net/VladimirAus/gitlab-for-php-developers-brisbane-php-meetup-2019jan30

PHP Events:
* Drupal 8 migration training (Brisbane [8-Feb], Melbourne [15-Feb]): http://bit.ly/dgtdau
* DrupalCamp Byron Bay [26-27 Apr]: http://www.drupalcampbyronbay.com
* PHP conference (Singapore, 24-25 June) : https://2019.phpconf.asia/
* Joomla! Day (Brisbane, 03-04 Aug) : https://www.joomladay.org.au/
* DrupalSouth (Hobart, 27-29 Nov) : https://drupalsouth.org/
