### ISSUE TITLE
8 types of automated testing for your PHP app - you won't believe #3!

### ISSUE THREAD

**Issue by tomtomau** [BrisPHP/meetups#18]
Clickbaity title, woo!

We've been establishing lots of different types of automated testing at different scopes of application that gives us varying degrees of certainty about our app working correctly.

I propose in this talk to discuss the approach more generally (keep finding new ways to tests), as well as run through each of the different ways of testing, with practical examples of how they work & how you can go back and begin applying them.

Disclaimer: by the time of this presentation, there may be more than 8 types 😈

**Comment by dpdme** [comment]
Sounds badass @tomtomau

**Comment by ndench** [comment]
Thanks for the great talk @tomtomau! [Here's a link to Tom's slides](https://slides.com/tomnewbyau/8-types-of-automated-testing-for-your-php-app/#/).
