### ISSUE TITLE
Code deployment at scale and why we suck

### ISSUE THREAD

**Issue by samueljamesmarshall** [BrisPHP/meetups#20]
Our failures and success deploying at scale at Neto eCommerce. Topics to cover:
- Supporting multiple application versions for production and development
- Overcoming slowness from artifacts with large file count and size
- Deploying to large groups of instances and managing traffic
- Importance of quality health checks
- Artifact standards
- Push (SSH) vs Pull (Agent) deployments

**Comment by ndench** [comment]
Thanks for submitting this Sam, I've scheduled you in the [next meetup](https://www.meetup.com/BrisPHP/events/257912534/) on the 29th of January. Really looking forward this.

**Comment by ndench** [comment]
Thanks for the awesome talk @samueljamesmarshall! Would you be able to add a link for your slides to this issue?

**Comment by samueljamesmarshall** [comment]
https://docs.google.com/presentation/d/1hYFWe9kB6Ma3JIpk-3BGJFZtXUgA-8VGawuFnxHzMy4/edit?usp=sharing
