### ISSUE TITLE
Offer to do a talk: Logging

### ISSUE THREAD

**Issue by wildcard27** [BrisPHP/meetups#21]
At Neto we have been making a few changes in how we handle logging. Since I've been Mariana-Trench-deep in this recently, I figured I could share what I have learned. I might even be able to help people from making mistakes that we have made.

If anyone has any particular part of logging that they would like me to cover, comment below.

**Comment by rodjsta** [comment]
I would love to see a presentation on logging.

**Comment by ndench** [comment]
@wildcard27 sorry for the late response. I think a logging talk would great! Some ideas for you to cover would be:

- How to effectively log while following the 12factor app
- What should you log?
- How do you get value out of the logs? ie. how to consume them

Our next meetup will likely be in the second half of April but we haven't picked a date yet. Would you be available to give the talk then?

Could you also provide the following:
Presenter name:
Talk name:
Talk length: 10 min/15 min/20 min
Talk synopsis:
Twitter handle (optional):

**Comment by wildcard27** [comment]
Thanks Nathan,

Great ideas for topics. I am not very familiar with the 12factor app way of handling logs but I will read up.

I should be available to give a talk at the next one, so long as my wife has given birth by then! She is due on 7th April so shouldn't be an issue.

Name: Matt Dillon
Talk length: ~15 mins
Talk Synopsis: Will post once I have worked it out!
~~Twitter handle~~ LinkedIn profile: https://www.linkedin.com/in/matt-dillon-9b45b5157

**Comment by ndench** [comment]
Awesome, thanks @wildcard27. I've scheduled you in for the [next meetup](https://www.meetup.com/BrisPHP/events/260160444/).

Just to let you know, we aren't able to connect laptops to the screen at CreditSense so we can't do demos. If you could provide your slide deck before the night as either a link or powerpoint file that would be awesome.

Also, the screen is 4 TV's put together, so the borders of the TV's go through the centre both vertically and horizontally and can sometimes butcher your slides if you have text directly on the lines, but it's usually pretty good, I just try not line up the text directly in the middle of the slide.

**Comment by ndench** [comment]
@wildcard27 has had to defer his talk until the next meetup, but never fear - we've filled the gap and this talk will still be happening!

**Comment by tomtomau** [comment]
Hi @wildcard27 keen to see you folks do logging at scale!

We've just announced the Q3 meetup - could you please confirm if you're available to talk that night?
https://www.meetup.com/BrisPHP/events/262052750/

Cheers!

**Comment by wildcard27** [comment]
This won't be a problem. @tomtomau , see you there

**Comment by wildcard27** [comment]
@tomtomau I am just doing some fine-tuning for my talk. So far it is about half an hour. Would you like me to shorten it down a little?

**Comment by ndench** [comment]
Hey @wildcard27, we normally try to keep talks around the 15-20 minute mark but feel free to go up to 30 minutes if you need to. Please don't go over that though as we have a few other talks to get through :smile:

**Comment by wildcard27** [comment]
My slides from last night: https://docs.google.com/presentation/d/1Wyckja7QDrJjWhDpee-yXIBMf9MVqiey2BXoQ3eqqSk/edit?usp=sharing

**Comment by tomtomau** [comment]
Champion, great job the other night!

[YouTube video of the talk](https://www.youtube.com/watch?v=Qm-QCdkX23U)
