### ISSUE TITLE
[Talk Offered] Reformat, Refactor, Replace

### ISSUE THREAD

**Issue by samlev** [BrisPHP/meetups#22]
**Presenter name**: Samuel Levy
**Talk name**: Reformat, Refactor, Replace
**Talk length**: 15 min - 20 min
**Talk synopsis**: A practical guide for bringing legacy software up to modern standards

**Comment by ndench** [comment]
Hi @samlev, thanks for the talk offer! It sounds like a great talk, are you available to do it at the [next meetup](https://www.meetup.com/BrisPHP/) (30th April)?

**Comment by ndench** [comment]
Thanks for the talk @samlev, kind of makes me wish I had a legacy codebase to try it out :joy:. Here's a link to [the slides](https://docs.google.com/presentation/d/1gIDc86pglNsjdFJJujX4sF07WmacFbE8HJigaLfyqZ4/edit?usp=sharing).
