### ISSUE TITLE
Tips for Mentoring a Junior Dev 

### ISSUE THREAD

**Issue by tomtomau** [BrisPHP/meetups#23]
Talk offered by @allyeastman 😀

Talk title: Tips for Mentoring a Junior Dev
Talk length: 15 min
Talk synopsis:

>Over the past 3 years, Ally has had her fair share of mentoring from devs with different skill levels and personalities.
In this talk, she will share tips around how to guide mentors, paired programming and helping juniors grow in their careers.

**Comment by allyeastman** [comment]
Hi Tom,

As promised here is the link to my presentation:
https://docs.google.com/presentation/d/10MPyVxGtFt2h0FrsNlXTF1C78r8sUm2keOx2CdcSTIc/edit?usp=sharing

Let me know if you have any troubles viewing it.

Thanks :)

**Comment by ndench** [comment]
I'm excited for this talk! It's been scheduled in for [the meetup tonight](https://www.meetup.com/BrisPHP/events/260160444/).

**Comment by ndench** [comment]
Thanks for the great talk @allyeastman I definitely took a lot from it :+1:
