### ISSUE TITLE
Discipline and Tough Love -- Imposing Standards and Quality

### ISSUE THREAD

**Issue by mounty1** [BrisPHP/meetups#24]
PHP is an interpreted language so it is possible for bugs to arise in deployment that could not make it through the build process in compiled languages;  type inconsistencies, "string typing" and undefined values.
At Credit Sense we are tackling this problem on several fronts concurrently:
  - Source code layout and typographical standards.
  - Larger-scale problems such as excessive complexity of functions.
  - Development of a set of system-testing scripts which will become a CI/CD harness.
  - Cleaning up the source to allow for static analysis.

This presentation is of what we are doing now, and where we are going with our quest to tame our code-bases.

**Comment by ndench** [comment]
This sounds like a great talk @mounty1. It would be awesome to have you present it at the next meetup (Q3, not tonight :joy:)!

**Comment by tomtomau** [comment]
Hi @mounty1 looking forward to this, I'm a big fan of brutally strict codebases :)

We've just announced the Q3 meetup - could you please confirm if you're available to talk that night?
https://www.meetup.com/BrisPHP/events/262052750/

Cheers!

**Comment by ndench** [comment]
Sad to hear that you can't do this preso at the next meetup @mounty1. Hope you can make it to the next one!

**Comment by ndench** [comment]
Hi @mounty1, we're planning to host the next BrisPHP meetup remotely in either late June or early July. Currently sorting out the logistics of streaming a meetup. Would you be available to do this talk?

**Comment by mounty1** [comment]
On Wed, 27 May 2020 16:06:18 -0700
Nathan Dench <notifications@github.com> wrote:

> Hi @mounty1, we're planning to host the next BrisPHP meetup remotely
> in either late June or early July. Currently sorting out the
> logistics of streaming a meetup. Would you be available to do this
> talk?

Sorry but I'm not so involved in the PHP world now so wouldn't be able
to give it the same focus as I could a year ago.  Changed employer,
changed responsibilities.

______________
Michael Mounteney

**Comment by ndench** [comment]
No problem, I'll just close out this issue. Hope everything is going great at `$newJob`!
