### ISSUE TITLE
Implement event-driven architecture using PHP & MySQL

### ISSUE THREAD

**Issue by andytruong** [BrisPHP/meetups#25]
At GO1, we have problem with RESTful driven and moving to event-driven  architecture.

The implementation in PHP & MySQL is much simpler than I thought. I would like to share my experience on how we are implementing and enjoy benefits it's giving:

- Problems with RESTful architeture
- Benefits from event-driven architeture
- Implementation & bright future

## Talk info

- Length: 20 min
- Twitter: @thehongtt

**Comment by tomtomau** [comment]
I'm keen as! Sounds like a great talk and others are already interested in it :)

We're not 100% on a date yet, but would you be interested in presenting this at the Q3 meetup?

**Comment by andytruong** [comment]
> would you be interested in presenting this at the Q3 meetup?

That's great. Thank you.

**Comment by tomtomau** [comment]
Hi @andytruong I'm so keen for this talk!

We've just announced the Q3 meetup - could you please confirm if you're available to talk that night?
https://www.meetup.com/BrisPHP/events/262052750/

Cheers!

**Comment by andytruong** [comment]
@tomtomau yeah, I confirm.

This is my draft https://slides.com/andytruong/event-driven-architecture

Thanks

**Comment by andytruong** [comment]
Slide for my talk:

[event-driven.key.zip](https://github.com/BrisPHP/meetups/files/3444545/event-driven.key.zip)

**Comment by ndench** [comment]
Thanks @andytruong! Is it possible to get these slides a link instead?

**Comment by andytruong** [comment]
@ndench  https://drive.google.com/file/d/1NGCHEv4FfNZwYU4KCCrtR0dOhfLaS4Kw/view
