### ISSUE TITLE
Refactoring to modern standards in a legacy Codebase

### ISSUE THREAD

**Issue by LabsCheckout** [BrisPHP/meetups#26]
The Squiz CMS is over 15 years old, and has never really had a coding standard (despite squizlabs/php_codesniffer) existing! 

As part of a modernisation effort, we're adding and improving tools (dependency injection, reducing CI average time, containers) so I'd like to present on how we improved our coding standards through moving from simpletest to phpunit, CI, Git Hooks and Local IDEs while supporting multiple versions of PHP (5.4 -> 7.3). 

It's very similar to #24 but with a different perspective (hopefully, I'll need to come along to the next meetup to make sure of that!)

**Comment by tomtomau** [comment]
Really keen to see this talk from Ben! Yay for code quality!

**Comment by LabsCheckout** [comment]
I've recreated this with my personal account, so I get notifications.
