### ISSUE TITLE
Refactoring to modern standards in a legacy Codebase

### ISSUE THREAD

**Issue by benfreke** [BrisPHP/meetups#28]
This is the same as #26, but I'm submitting it as me and not the corporate user.

The Squiz CMS is over 15 years old, and has never really had a coding standard (despite squizlabs/php_codesniffer existing!)

As part of a modernisation effort, we're adding and improving tools (dependency injection, reducing CI average time, containers) so I'd like to present on how we improved our coding standards through moving from simpletest to phpunit, CI, Git Hooks and Local IDEs while supporting multiple versions of PHP (5.4 -> 7.3).

It's very similar to #24 but with a different perspective (hopefully, I'll need to come along to the next meetup to make sure of that!)

**Comment by ndench** [comment]
Hi @benfreke, we're planning to host the next BrisPHP meetup remotely in either late June or early July. Currently sorting out the logistics of streaming a meetup. Would you be available to do this talk?

**Comment by benfreke** [comment]
I'm sure I can knock something together if there aren't any other volunteers

**Comment by ndench** [comment]
We've scheduled this talk for our next meetup: [Q2 2020](https://www.meetup.com/BrisPHP/events/271156919/) which will be taking place online 🎉.

**Comment by benfreke** [comment]
[Presentation Slides](https://github.com/BrisPHP/meetups/files/4944817/Refactoring.to.modern.standards.in.a.legacy.codebase.-.Ben.Freke.-.BrisPHP.2020.Q2.pdf)

**Comment by ndench** [comment]
Thanks for the great talk and for posting your slides @benfreke! I look forward to hearing more about the huge refactor Squiz is going through.
