### ISSUE TITLE
Developing a PHP application with Skaffold

### ISSUE THREAD

**Issue by ndench** [BrisPHP/meetups#29]
Tim Colbert from CreditSense has offered to do this talk, it will take place at the [next meetup](https://www.meetup.com/BrisPHP/events/262052750) on July 30. More details to come.

**Comment by s3than** [comment]
The talk will look at a basic development application using Symfony, Skaffold and Kubernetes

> Skaffold is a command line tool that facilitates continuous development for Kubernetes applications. You can iterate on your application source code locally then deploy to local or remote Kubernetes clusters.

I'll be going over the configuration of the various components and will provide a link to example code at the end of the talk.

**Comment by tomtomau** [comment]
Hey @s3than thanks for talking at the Meetup. Could you please share your code/webpage?

**Comment by ndench** [comment]
Here are Tim's slides: [Developing with Kubernetes and Skaffold.pptx](https://github.com/BrisPHP/meetups/files/4238600/Developing.with.Kubernetes.and.Skaffold.pptx)
