### ISSUE TITLE
Caching PHP Web Pages

### ISSUE THREAD

**Issue by ccaway** [BrisPHP/meetups#3]
Hi, I thought it would be great to have somebody speak on web server and PHP page caching

**Comment by ndench** [comment]
Hey @ccaway, are you talking about caching arbitrary data or something specific?
ie. 
- results from a database or api
- an entire page
- some data related to the user
- or something else entirely

**Comment by ndench** [comment]
This talk will take place at the next meetup: https://www.meetup.com/BrisPHP/events/247341104/

**Comment by ndench** [comment]
I'll be adding the slides to this issue very soon.

**Comment by ndench** [comment]
Josh has provided the slides for his talk on PHP Caching:

* [.pptx format](https://github.com/BrisPHP/meetups/blob/master/materials/php_caching/brisphp_php_caching_march_2018.pptx)
* [.odp format](https://github.com/BrisPHP/meetups/blob/master/materials/php_caching/brisphp_php_caching_march_2018.odp)
