### ISSUE TITLE
WordPress for Laravel Developers

### ISSUE THREAD

**Issue by samlev** [BrisPHP/meetups#30]
**Presenter name**: Samuel Levy
**Talk name**: WordPress for Laravel Developers
**Talk length**: 30 min
**Talk synopsis**: So you want to use Laravel, but _The Man_ insists that you use WordPress? Well never fear! This talk explores how the internals of WordPress themes work, and how you can use your shiny Laravel toolset in WordPress theme development.

**Comment by ndench** [comment]
Thanks for the very entertaining talk @samlev. Still can't believe you made WordPress execute Laravel :joy:.

Here's a link to [Sam's slides](https://docs.google.com/presentation/d/1tfICGg2nhqlO14KAECk8VeUxNSAo8QsWO5Ah1eJcnR4/edit#slide=id.p).
