### ISSUE TITLE
The ins and outs of CQRS

### ISSUE THREAD

**Issue by ndench** [BrisPHP/meetups#31]
This talk has been offered by Ben Plunkett from Neto after their recent deep dive and implementation of CQRS. Can't wait to hear it at the [next meetup](https://www.meetup.com/BrisPHP/events/264746864/).

We'll fill out the following details in a comment:

Presenter name: 
Talk name: 
Talk length: [10/15/20 minutes[
Talk synopsis: [a short sentence or two]
Socials: (optional twitter/linkendin/etc for street cred)

**Comment by benplunkett** [comment]
Here's the slides:
https://docs.google.com/presentation/d/1xNbIaIx7NqHF54quW9d5k56KTdg8ZeXGrgktDpRqNyg/edit?usp=sharing

Presenter name: Ben Plunkett
Talk name: Command-Query Responsibility Segregation
Talk length: 20 minutes
Talk synopsis: Brief overview of the CQRS pattern and when/how it should be used
Socials: https://twitter.com/ben_plunkett

**Comment by ndench** [comment]
Thanks for that @benplunkett, great talk!
