### ISSUE TITLE
Laracon Wrap Up

### ISSUE THREAD

**Issue by ndench** [BrisPHP/meetups#32]
This talk has been offered by Robert Wilde who will be dutifully taking notes all thought Laracon! Can't wait to hear it at the [next meetup](https://www.meetup.com/BrisPHP/events/264746864/).

We'll fill out the following details in a comment:

Presenter name: 
Talk name: 
Talk length: [10/15/20 minutes[
Talk synopsis: [a short sentence or two]
Socials: (optional twitter/linkendin/etc for street cred)

**Comment by robwilde** [comment]
Presenter name: Robert Wilde
Talk name: Laracon AU 2019 review
Talk length: 15 minutes
Talk synopsis: My take on LaraconAU 2019 as First timer, should you attend?
Socials: @mrwilde | mrwilde.com | figjam@mrwilde.com

**Comment by ndench** [comment]
@robwilde thanks for the great talk last night! Can you post a link to your slides please?

**Comment by robwilde** [comment]
[Laracon AU 2019 Talk.pdf](https://github.com/BrisPHP/meetups/files/4189621/Laracon.AU.2019.Talk.pdf)

**Comment by ndench** [comment]
Thanks @robwilde!
