### ISSUE TITLE
3 years of scaling Laravel

### ISSUE THREAD

**Issue by theHarvester** [BrisPHP/meetups#34]
I can present a talk on how we've scaled Laravel for the last few years and how we overcame roadblocks.

**Comment by tomtomau** [comment]
Thanks James, looking forward to it!

**Comment by ndench** [comment]
Thanks @theHarvester, can't wait. Can you fill out the following to give us some deets we can post on LinkedIn/Instagram/Meetup?

Presenter name:
Talk name:
Talk length: [10/15/20 minutes[
Talk synopsis: [a short sentence or two]
Socials: (optional twitter/linkendin/etc for street cred)

**Comment by tomtomau** [comment]
Thanks @theHarvester!

Slides are available [here](https://www.canva.com/design/DAD0_fCRRi0/DFV1JB-nx_6eCydufFZfUA/view?utm_content=DAD0_fCRRi0&utm_campaign=designshare&utm_medium=link&utm_source=publishsharelink)
