### ISSUE TITLE
A talk on security / OAuth / JWTs / OWASP / ...

### ISSUE THREAD

**Issue by bendechrai** [BrisPHP/meetups#36]
Hi there! Further to a chat with Tom on meetup, here's a placeholder offer to talk at the next (June) meetup :smile:

**Comment by rodjsta** [comment]
Hi @bendechrai, sounds like it would be a great talk.

**Comment by ndench** [comment]
Hi @bendechrai, thanks for the talk offer! We're planning to host the next BrisPHP meetup remotely in either late June or early July. Currently sorting out the logistics of streaming a meetup. Would you still like to do this talk?

**Comment by bendechrai** [comment]
Hey @ndench - still happy to give a talk :)

**Comment by ndench** [comment]
We've scheduled this talk for our next meetup: [Q2 2020](https://www.meetup.com/BrisPHP/events/271156919/) which will be taking place online 🎉.

@bendechrai I've sent you a message on the Brisbane Slack workspace to organise logistics.

**Comment by ndench** [comment]
Thanks for the awesome talk @bendechrai. Would you mind posting a link to your slides on this issue?
