### ISSUE TITLE
Laracon Online 2020 recap

### ISSUE THREAD

**Issue by mrwilde-ixa** [BrisPHP/meetups#37]
Presenter name: Robert Wilde
Talk name: Laracon Online 2020 Recap
Talk length: 15 minutes
Talk synopsis: Recap on the presentations from last Thursday morning. Give a quick rundown on the speakers, what they spoke about with a final roundup and weather it is value for money
Socials: 
https://twitter.com/mrwilde
https://mrwilde.com

**Comment by robwilde** [comment]
[PHP Meetup March 2020.pdf](https://github.com/BrisPHP/meetups/files/4295967/PHP.Meetup.March.2020.pdf)

**Comment by ndench** [comment]
Thanks @mrwilde-ixa!
