### ISSUE TITLE
Setting up a project in any PHP framework (Slim PHP)

### ISSUE THREAD

**Issue by ndench** [BrisPHP/meetups#4]
I've only ever had experience with Symfony and could give a talk on that, but would also be good to get talks on other frameworks, ie.

- Laravel
- Yii
- CakePHP
- etc.

**Comment by nk2580** [comment]
Can do slim if someone wants to know.

It’s real simple and super powerful

**Comment by ndench** [comment]
Yeah I'd be interested in learning about Slim. Have you got anything in particular in mind you'd like to talk about? Or just a sort of "Slim Into"?

**Comment by nk2580** [comment]
Completely spaced on the date. Might have to do this at the next one

Can do a general overview.
Common uses, different setups, that sort of thing.

**Comment by ndench** [comment]
@nk2580 I didn't mean for you to do the talk tonight haha. We already had 4 talks lined up anyway. It would be great to lock it in for the next meetup though, it'll be happening in the next 2-3 months :smile:

**Comment by nk2580** [comment]
Yeah done. I’ll prepare one in advance

**Comment by ndench** [comment]
That's awesome, I'll be sure to let you know as soon as we've landed on a date for the next meetup!

**Comment by ndench** [comment]
@nk2580 are you good to present about slim at the next meetup? We haven't released the meetup yet, but it'll be on the 31st of May.

**Comment by nk2580** [comment]
Good to go.. anything in particular you’d like to see covered?

**Comment by ndench** [comment]
I think an overview of slim, maybe comparisons to other popular frameworks (ie. symfony, laravel, etc) and reasons to use slim?

**Comment by ndench** [comment]
We've just announced the next meetup for the 31st of May: https://www.meetup.com/BrisPHP/events/250153519/.

I've named your talk "The beauty of Slim PHP" @nk2580, but feel free to pick a different name and I'll update it. I just needed a name to put on the event :joy:

**Comment by ndench** [comment]
Thanks for the talk @nk2580, I always enjoy hearing about new frameworks. [Here's a link](https://drive.google.com/file/d/1d9tta-8dBH50KGVTDltUQrxnFIX5ccss/view?usp=sharing) to the presentation so others can find it.
