### ISSUE TITLE
PHP in AWS Lambda, an introduction

### ISSUE THREAD

**Issue by benplunkett** [BrisPHP/meetups#44]
Presenter name: Ben Plunkett
Talk name: PHP in AWS Lambda, an introduction
Talk length: 20 minutes
Talk synopsis: How to get PHP running in Lambda and our experience running it at scale
Socials: https://twitter.com/ben_plunkett

**Comment by ndench** [comment]
We've scheduled this talk for our next meetup: [Q2 2020](https://www.meetup.com/BrisPHP/events/271156919/) which will be taking place online 🎉.

@benplunkett I've sent you an email to organise logistics.

**Comment by ndench** [comment]
Thanks for the great talk @benplunkett, I'd love to hear how your lambda CI pipeline works once you get it up and running. Can you please post a link to your slides and any other resources on this issue?
