### ISSUE TITLE
Get your Git on! Atomic commits and Git rebase -i and why they are so awesome

### ISSUE THREAD

**Issue by robwilde** [BrisPHP/meetups#45]
Presenter name: Robert Wilde
Talk name: Get your Git on! Atomic commits and Git rebase -i and why they are so awesome
Talk length: 20+ minutes
Talk synopsis: Moving from single developer using git for years to a team with Merge/Pull requests I realised I didn't know Git as well as I should or could. Then I found out about atomic commits and the best thing ever, git rebase -i and how it can make your MR/PR's so beautiful and easy to read.
Will also demo so really cool features of PHPStorm while doing the demo.
It may save your life someday :)
Socials: https://twitter.com/mrwilde

**Comment by ndench** [comment]
This talk is scheduled for the [next meetup](https://www.meetup.com/BrisPHP/events/278038611/) on May 25.

**Comment by ndench** [comment]
Here is the [recording](https://www.youtube.com/watch?v=BgviY3GR8uk&t=4500s) of this talk. @robwilde could you please link us to your slides?

**Comment by robwilde** [comment]
Here are the slides peoples...
[MR Wilde - Get Good with Git.pdf](https://github.com/BrisPHP/meetups/files/6543607/MR.Wilde.-.Get.Good.with.Git.pdf)
