### ISSUE TITLE
Looking for a local PHP contract developer

### ISSUE THREAD

**Issue by tecbanc** [BrisPHP/meetups#47]
We're Brisbane based and in need of PHP assistance, both in minor repairs of an existing site, and a couple of larger projects. We'd prefer to work with someone local, so if anyone is around Brisbane or the Gold Coast and is looking for some contract work, please let me know. Many thanks, stay safe. Cheers.

**Comment by ndench** [comment]
Hi @tecbanc 

I'm one of the organisers or the meetup and our goal is to build a really great PHP community. One of the ways we're trying to do that is to keep the meetup free of "recruiter spam". We understand that people are looking for PHP developers, and our members are even looking for new opportunities. So it's fine to look for devs at our meetup, we just ask that you be an active part of our community first.

So if you'd like to attend some of our meetup and possibly even offer/request a talk and get to know our members, then we're completely fine with you advertising your opportunities through us. I'm sure you understand why we don't want people that aren't involved in our community to be using our meetup to approach our members.

**Comment by tecbanc** [comment]
No problem, thanks for the heads up. Cheers.
