### ISSUE TITLE
Ways of Working at Neto

### ISSUE THREAD

**Issue by projectliamphelps** [BrisPHP/meetups#48]
Hi everyone,
I would like to offer a talk on Neto's ways of working. For a few years Neto tech departments ways of working have evolved to meet our needs and what we want to achieve. I would like to offer a 30min talk on how Neto tech department works and what we have learnt over the last few years.

**Comment by ndench** [comment]
This talk has been scheduled for our [next meetup](https://www.meetup.com/BrisPHP/events/274172329/) on Tuesday Nov 17.

**Comment by ndench** [comment]
Thanks for the talk last year @projectliamphelps. If you still have a copy of your slides, could you upload them here please?
