### ISSUE TITLE
Accessibility for the backend

### ISSUE THREAD

**Issue by samlev** [BrisPHP/meetups#50]
**Time:** 15 minutes, I guess?

**About the talk:**

There's a lot of information about what accessibility looks like on the front-end of a website, but what does accessibility look like behind the user interface?

This is a quick talk about what accessibility means inside the codebase, and why it matters.

**Comment by tomtomau** [comment]
Lock it in

**Comment by ndench** [comment]
Thanks for the great talk last year @samlev! If you still have your slides, could you upload a copy here please?
