### ISSUE TITLE
Hiring PHP Developer

### ISSUE THREAD

**Issue by maxwasley** [BrisPHP/meetups#53]
Hi all, 

I am looking for a PHP Developer, based in Brisbane, to work on a pretty interesting Aid program. 

Let me know if you have any questions, and am keen to come and say hi at the next meetup. 

https://www.seek.com.au/job/51903323

Max

**Comment by rodjsta** [comment]
That looks like an interesting role.

**Comment by ndench** [comment]
Hope you found a developer @maxwasley!
