### ISSUE TITLE
Software Rewrites: The Company Killer 

### ISSUE THREAD

**Issue by ndench** [BrisPHP/meetups#6]
This talk will take place at the [next meetup](https://www.meetup.com/BrisPHP/events/247341104/) and will focus on the experiences had while doing a full rewrite, why you shouldn't do rewrites, and what you should do instead.

**Comment by julzelements** [comment]
Relevant: https://www.joelonsoftware.com/2000/04/06/things-you-should-never-do-part-i/

**Comment by ndench** [comment]
Here's the slides from James' talk on the 1st of March 2018: https://docs.google.com/presentation/d/1-UVfzG5MP6spJ221M1NxALkJvMF4u1uEGf9c5dcTowg/edit#slide=id.p
