### ISSUE TITLE
Offer: Building an application to scale on Laravel Vapor

### ISSUE THREAD

**Issue by michaeldyrynda** [BrisPHP/meetups#61]
Infinite scale on serverless infrastructure is possible, but not without some important considerations.

In this talk, I run through some of the overlooked limitations in scaling a Laravel application to cater to "infinite scale" on AWS with Laravel Vapor, options to work around them, and the approaches we took with [thenping.me](https://thenping.me).

**Comment by ndench** [comment]
This talk has been scheduled for the [next meetup on August 31](https://www.meetup.com/BrisPHP/events/279626702/), I'm looking forward to it!

**Comment by ndench** [comment]
Thanks for the great talk last month @michaeldyrynda! Any chance you can link your slides and various blog posts you've created since then to this issue?

**Comment by michaeldyrynda** [comment]
For sure:

* Post with the [presentation and slides](https://dyrynda.com.au/blog/presentation-building-an-application-to-scale)
* Post on [configuring Grafana Cloud to visualise CloudWatch metrics](https://dyrynda.com.au/blog/monitoring-laravel-vapor-with-grafana-cloud)
