### ISSUE TITLE
Securing PHP 

### ISSUE THREAD

**Issue by developersteve** [BrisPHP/meetups#63]
According to Wappalyzer PHP is used in 79% of website backends. As a user and a developer of PHP for many years I've used it extensively for many projects, especially using open source Libraries and platforms. In this talk we are going to look at some ways to write secure PHP code and some things to keep in mind with open source use. Also we are going to look at some best practices to ensure application security.

**Comment by ndench** [comment]
Thanks for the great talk last month @developersteve. Any chance you can add a link to your slides and perhaps any demo materials you have to this issue?
