### ISSUE TITLE
WebP images using Blade

### ISSUE THREAD

**Issue by dnabeast** [BrisPHP/meetups#69]
Presenter name: Dan Beeston
Talk name: WebP in the Pool
Talk length: 15 minutes
Socials: @dnabeast
Talk synopsis: We're all versed in using Jpeg images but there are smaller and better options available. Using them is easy but making sure users on old browsers can see them, and providing alt version for retina displays, adds complexity. Dan will discuss the current solutions to the problem as well as demonstrate his Laravel package that automates the process.

**Comment by ndench** [comment]
Thanks for the offer @dnabeast! I'll reach out when we have scheduled the next meetup to see if you're available :smile:

**Comment by ndench** [comment]
Hey @dnabeast, just confirming the meetup is tomorrow night at the Neto offices in Fortitude Valley. Will you be presenting in person or online?

**Comment by dnabeast** [comment]
I'll be there in person. I'll log into my google account there and run the
slideshow from one of your computers if that's okay.

**Comment by ndench** [comment]
Yep, that's cool. If you post a link to your slides here you won't even need to login.

**Comment by dnabeast** [comment]
I think this is right.

https://docs.google.com/presentation/d/e/2PACX-1vR6--_VxiN40qsj7PjGVDFeSzBFPsWQVglfGEoJf6PPSH1mQBHWY_eIwi_cqOG7VYdqFe0r0RsI9Hny/pub?start=false&loop=false&slide=id.p

**Comment by ndench** [comment]
Thanks for the great talk last night @dnabeast. Here's a link to [the recording](https://www.youtube.com/watch?v=2aSGg2FfP2k)
