### ISSUE TITLE
[OFFER] Sharing some testing experiences when refactoring legacy code

### ISSUE THREAD

**Issue by dkaitou** [BrisPHP/meetups#73]
Presenter name: Ming
Talk name: Sharing some testing experiences when refactoring legacy code
Talk length: 15 mins
Socials: https://www.linkedin.com/in/mingwei-zhang-tech/
Talk synopsis: 
When we are trying to replace legacy features with new architecture and new code, we went through a lot of problems. 
One of the hardest was making sure it matches with existing business requirements.  
To be able to achieve that, we used layers of the testing approaches such as "unit testing", "scenario testing" and "regression testing".
Hope this talk can help someone to rebuild their system with minimum negative impacts.

**Comment by ndench** [comment]
Thanks for the offer @dkaitou! Our next meeting will be early next year, probably towards the end of February or start of March. I'll let you know when we've set a date . I'd really love to see this talk.

**Comment by ndench** [comment]
Hey @dkaitou, we're looking at having the next meetup on Wednesday the 2nd of March at CreditSense. Would you be available to do this talk then?

**Comment by dkaitou** [comment]
@ndench sounds good.

**Comment by ndench** [comment]
The meetup has been [announced](https://www.meetup.com/BrisPHP/events/283986031/)!

**Comment by ndench** [comment]
Hey @dkaitou, we've unfortunately had to reschedule the BrisPHP meetup due to the floods. I'll let you know once we pick a new date (should be in the next few weeks). Hopefully you're still able to do your talk!

**Comment by ndench** [comment]
Thanks for the talk last night @dkaitou! You had some really great approaches to testing legacy code. Here's a link to his [slides](https://docs.google.com/presentation/d/1odqNQDMDagBjz5dnyqF5ceguSIi5iBfECylptSUU8Nk/edit#slide=id.p) for future reference.

**Comment by dkaitou** [comment]
[Test on legacy code.pdf](https://github.com/BrisPHP/meetups/files/8447502/Test.on.legacy.code.pdf)

Please refer to the attached PDF for the PPT.
