### ISSUE TITLE
[OFFER] Keep Thinking Like a Hacker

### ISSUE THREAD

**Issue by valorin** [BrisPHP/meetups#74]
Presenter name: Stephen Rees-Carter
Talk name: Keep Thinking Like a Hacker
Talk length: 30minutes (but I can compress it down if this is too long)
Socials: https://twitter.com/valorin
Talk synopsis: 
What happens if a hacker breaks through your app, and gets to your server? You missed one tiny thing, and now the hacker is doing whatever they want on your server… How do you stop this from turning into a catastrophic event?
We’re going to assume the role of a hacker who has broken through the code, and has access to the server. We’ll go from there, hacking our way around, seeing what we have access to. While at the same time, adding layers of defence (as the site owner) to try and stop an impending catastrophic breach.

_Note: I will need to use my laptop to present._

**Comment by ndench** [comment]
Thanks @valorin, this talk sounds awesome. It's been scheduled in the [next meetup](https://www.meetup.com/BrisPHP/events/283986031/) on March 2nd.

**Comment by ndench** [comment]
Unfortunately we've had to postpone this talk due to the floods in Brisbane. We'll reschedule for sometime in the next few weeks :crossed_fingers:

**Comment by ndench** [comment]
This talk occurred on [July 5 2022](https://www.meetup.com/brisphp/events/286453642/)
