### ISSUE TITLE
PHP: where did it come from and why is it so ubiquitous?

### ISSUE THREAD

**Issue by julzelements** [BrisPHP/meetups#8]
I've never used PHP.
I'm a late career changer.
One of my biggest frustrations is not understanding why I am using a framework. What problem is it solving? More importantly: How did things used to be?

I would like a history lesson of the web and PHPs role in the proceedings. What PHP started out doing. What it does now. 

This will make me more effective when I 'encounter it' in the wild.

**Comment by julzelements** [comment]
No, no no! I have never used PHP. I'm hoping someone will GIVE this talk.

**Comment by tomtomau** [comment]
I'll take this one, will be fun to research!

**Comment by ndench** [comment]
Ah fair enough @julzelements my bad, misread it.

**Comment by dpdme** [comment]
Thanks @tomtomau I'm looking forward to this!

**Comment by ndench** [comment]
This talk will be going ahead at our next meetup on the 31st of May: https://www.meetup.com/BrisPHP/events/250153519/. Thanks @tomtomau!

**Comment by ndench** [comment]
Thanks for the talk last night @tomtomau was very enlightening. 

Here is a link to the presentation fro anyone that's looking for it: https://slides.com/tomnewbyau/24-years-php
